### PR TITLE
Sqflite compat pr

### PR DESCRIPTION
**Pull request by JanezStupar**
These changes are a result of my work on an implementation of sqlite CRDT implementation for Drift (see: https://github.com/JanezStupar/drift/tree/sqlite_crdt/drift_crdt).

My work relies on the work of @cachapa (`sql_crdt` and `sqlite_crdt`) libraries and Simon Binder's `drift_sqflite` library.

The changes are mostly related to expansion of the support for the sqflite API within `sql_crdt` of the scope that was necessary to get the `drift_crdt` working and some refactoring to avoid duplicate implementation.

Only new features are the migration within `sql_crdt.dart` and a "table of special queries" within `base_crdt.dart`.

I felt like those were appropriate places to dump the new features.

Let me know if you are open to accepting this contribution and what changes you feel need to be made to make them acceptable.

### CODE REVIEW

**Comment by cachapa** [comment]
On the surface this seems like a lot of code to support one specific ORM.
The changes to `database_api.dart` alone are enough to give me pause, as they cascade into extra work for every downstream implementation - granted there are only two right now (`sqlite_crdt` and `postgres_crdt`), but the goal was to keep them as minimal as possible.

Don't get me wrong, Drift is a great project, and `sql_crdt` probably wouldn't have been possible without it but that doesn't mean we have to provide a complete implementation for their whole stack.

Maybe I'm too unfamiliar Drift as I never used it, but I wonder if a `drift_crdt` wouldn't be better implemented in the other way around: forking Drift and replacing `sqflite` with an extension (or fork) of `sqlite_crdt` implementing the rest of the `sqflite` API.

In any case I am thankful for your contribution but I don't think that it fits the goals for this project.
I'm closing this PR for now but I'm happy to continue the discussion here.

**Comment by JanezStupar** [comment]
Thank you for your attention.

It is not about supporting one specific ORM, at least not exclusively. The changes I proposed have a lot more to do with compatibility with sqlite in broad and sqflite in the narrow sense. 

Based on the work I did I am pretty sure you will run into these same issues down the road when your work gets more adoption.

With that out of the way. I agree with you upon reflection. The sqlite specific changes I forced into sql_crdt really don't make sense when looked at in the context of say postgres.

I am looking at this as I write this. I will come back with a different approach soon - one that is better fitted to the situation at hand and the scope you have in mind.

**Comment by cachapa** [comment]
Thank you, but I do encourage you to discuss your proposed technical implementation before putting in the work as it saves us both a lot of time.

Can you expand on what you meant by "you will run into these same issues down the road"?

**Comment by JanezStupar** [comment]
First off I think you misunderstood the nature of the `rawUpdate`, `rawInsert`... methods. They are not meant to bypass the CRDT at all. They are merely a reflection of the sqflite APIs (see: https://pub.dev/documentation/sqflite/latest/sqlite_api/Database-class.html - e.g. `query` vs `rawQuery` methods)

In fact the API implemented in the `sqlite_crdt` is misnamed. The `query` method has the signature of the `rawQuery` method from Sqflite. The reason why I added them is because the client I am using is using the raw SQL statement API instead of parameterized `query` like API. 

However I agree that they should not be within `sql_crdt` library. But they cannot be implemented in `sqlite_crdt` - where they fit for sure, due to the private nature of the code within `base_crdt`.

Next issue is the isolation of the database connection to the `base_crdt`. While I can appreciate the sentiment I ran into an issue while implementing the transaction. Sqflite rolls back the transaction on error. `sql_crdt` implementation however does not and when trying to make `sqlite_crdt` compliant to the sqflite API this became an issue.

And since `sql_crdt` guards its implementation so closely I can not implement the required changes in superclass of TransactionCrdt. To do what is needed I would have to basically fork everything - to the extent of my knowledge.

And it seems to me these issues will crop up whenever somebody tries to include your libs within their existing project.

On the topic of migrations, I personally feel like that is a nice optional thing to have. Especially when it can be implemented in a database agnostic way. But that is a matter of personal preference. So by putting them inside the `sql_crdt` I though I was killing two birds with one stone. 

But the real issue is again, that since the database connection cannot be accessed by the downstream code it is not possible for my own database library (whatever that is) to extend the behaviour of `sqlite_crdt` in a pragmatic fashion. And I have noted your suggestion to open another database connection. However it is my understanding that in sqflite it is assumed there is only one open connection at any given time to the database at this point in time. I could be wrong on this one.

So in a nutshell it would seem to me that the decision to keep so much of the base stuff private is really detrimental to brownfield scenarios and I am pretty sure that other developers will be affected in the future. I can understand you find this approach elegant and it might make sense for your use case, but it has already costed me a lot of time to this point (not enough for me to warrant implementing CRDT from scratch, mind you) and while it has facilitated me learning about CRDTs by proxy (which is good too) it doesn't have to be like that.

Have you considered using the '@protected' decorator instead?

p.s.: I did some prototyping to see whether I missed something when originally implementing these changes. And I realized that without making CRDT code more accessible I really don't have an alternative.

**Comment by cachapa** [comment]
I see what you mean by the `rawQuery` methods. You're right that I misunderstood their intent.

> In fact the API implemented in the sqlite_crdt is misnamed.

It's not misnamed, it's only incidental that it has the same name as a method from the `sqflite` package. As I said before this library is intended to be a generic implementation of CRDTs backed by an SQL engine.
Moreover `sqlite_crdt` is an implementation of CRDTs backed by a Sqlite engine - not a `sqflite` engine - otherwise I would've named it `sqflite_crdt`.
The fact that `sqlite_crdt` uses `sqflite` is an implementation detail. It may change in the future (however unlikely).

> Next issue is the isolation of the database connection to the base_crdt. While I can appreciate the sentiment I ran into an issue while implementing the transaction. Sqflite rolls back the transaction on error. sql_crdt implementation however does not and when trying to make sqlite_crdt compliant to the sqflite API this became an issue.

Can you provide a bit more detail here? I'm under the impression that `sqlite_crdt` does roll back transactions. It uses the `sqflite` `transaction()` method which I believe handles cleanup.

> On the topic of migrations, I personally feel like that is a nice optional thing to have. Especially when it can be implemented in a database agnostic way. But that is a matter of personal preference. So by putting them inside the sql_crdt I though I was killing two birds with one stone.

That is a good point, and one I might come back to later even if at this moment I'm still trending to no.
The only suggestion I would make is to separate such pieces of work into separate PRs since it makes PRs smaller, easier to review and to focus the discussion.
I actually mention this in the [contribution guidelines](https://github.com/cachapa/sql_crdt/blob/master/CONTRIBUTING.md).

> But the real issue is again, that since the database connection cannot be accessed by the downstream code it is not possible for my own database library (whatever that is) to extend the behaviour of sqlite_crdt in a pragmatic fashion. And I have noted your suggestion to open another database connection. However it is my understanding that in sqflite it is assumed there is only one open connection at any given time to the database at this point in time. I could be wrong on this one.

Actually that was not a suggestion, just a statement of fact. I really don't think you should be accessing your CRDT databases using other tools unless it's read-only.
The correct way to access the underlying database is to update the version and use the `onUpgrade` callback to get a database object that's closer to bare metal.
Naturally this also opens the door to making invalid changes to the CRDT, but it does it in a limited space.

Maybe it would be helpful if you could provide examples of things you'd like to do with direct access to the underlying database that you can't do now.

To be clear I have migrated hundreds of thousands of users from brownfield applications to `sqlite_crdt` and `postgres_crdt` both in mobile apps and backend, and managed to do it with the exitsting API.
So I'm wondering if I'm missing some use case, or if perhaps the documentation isn't clear enough.

**Pull request closed without merging**
